-- Create the Admins Table
CREATE TABLE Users (
    admin_id INT not null generated by default as identity primary key,
    user_name VARCHAR(255),
    user_password VARCHAR(255) -- Store hashed passwords
);

-- Create the Patients Table
CREATE TABLE Patients (
    patient_id INT not null generated by default as identity primary key,
    patient_name VARCHAR(255),
    patient_surname VARCHAR(255),
    patient_phone_number VARCHAR(20),
    patient_birth_date DATE,
    patient_address TEXT
);

-- Create the Appointments Table
CREATE TABLE Appointments (
    appointment_id INT not null generated by default as identity primary key,
    patient_id INT REFERENCES Patients(patient_id),
    appointment_time TIMESTAMP,
    appointment_diagnose TEXT,
    appointment_cure_type TEXT,
    appointment_price decimal(15, 3),
    appointment_paid decimal(15, 3),
    appointment_is_visited BOOLEAN DEFAULT FALSE 
);

